### ISSUE TITLE
wrong id in json files

### ISSUE THREAD

**Issue by kalidor** [canonical/ubuntu-security-notices#2]
Hi, first of all thanks for making those USN available in this format.
I notice there is at least 2 USNs `612-10` and `612-11` with a wrong id ("USN-" is missing) in their respective json file. Since all other USN are using `USN-XXX-YY`:

- 612-10.json
```json
"action": "In general, a standard system upgrade is sufficient to effect the\nnecessary changes.\n",
  "id": "612-10",
  "cves": [
    "https://launchpad.net/bugs/230197"
  ]
```
- 612-11.json
```json
"action": "In general, a standard system upgrade is sufficient to effect the\nnecessary changes.\n",
  "id": "612-11",
  "cves": [
    "http://www.ubuntu.com/usn/usn-612-1",
    "http://www.ubuntu.com/usn/usn-612-3",
    "http://www.ubuntu.com/usn/usn-612-8",
    "http://www.ubuntu.com/usn/usn-612-9"
  ]
```

And I have a question, i didn't find a LSN in this repo nor other repo in canonical. If there a chance we can see the same kind of repo with LSN ? or we will have to keep using the API ?

**Comment by dodys** [comment]
Thanks for reporting this, I've just pushed a fix for it.

Regarding LSNs, no, we have no plans yet of having them here.
You can get a JSON for LSNs from the website itself, e.g. https://ubuntu.com/security/notices/LSN-0101-1.json
Hope this helps in the meantime.

**Comment by eslerm** [comment]
Just to note, https://ubuntu.com/security/usn now redirects to https://ubuntu.com/security/notices.

There are several similar link rot cases, where the url slug schema has changed over time (e.g., `usn.ubuntu.com` is no longer used). In my cve triage tooling, I have functions to fix USN urls in the Ubuntu CVE Tracker, which could then be used to update USNs ( see `reference_usn_lint()` in https://git.launchpad.net/~eslerm/ubuntu-cve-tracker/tree/scripts/vulnerability_translate.py?h=cve-translate#n1133).

**Comment by dodys** [comment]
> Just to note, https://ubuntu.com/usn now redirects to https://ubuntu.com/security/notices.
> 
> There are several similar link rot cases, where the url slug schema has changed over time (e.g., `usn.ubuntu.com` is no longer used). In my cve triage tooling, I have functions to fix USN urls in the Ubuntu CVE Tracker, which could then be used to update USNs ( see `reference_usn_lint()` in https://git.launchpad.net/~eslerm/ubuntu-cve-tracker/tree/scripts/vulnerability_translate.py?h=cve-translate#n1133).

Hi Mark,

That doesn't relate to the issue described here.
Also that URL is just how it is in the USN database, it is only on old USNs and we have no plan of updating old USNs. We would only consider addressing it if the redirection stops working.
