### ISSUE TITLE
Source Tracking Bug in USN to OSV Conversion

### ISSUE THREAD

**Issue by SURENKUMAR-0212** [canonical/ubuntu-security-notices#3]
### How do you classify the sources that for the following example

![image](https://github.com/canonical/ubuntu-security-notices/assets/119495918/558da57a-354d-49ca-9733-f1281129b24c)

Here there are 9 different sources but `after converting usn2osv` only the last source and binaries respected to that were tracked in the osv format file which is added below

Before converting
[5390-1.json](https://github.com/canonical/ubuntu-security-notices/files/15319252/5390-1.json)

After converting usn2osv
[USN-5390-1.json](https://github.com/canonical/ubuntu-security-notices/files/15319263/USN-5390-1.json)

**Comment by SURENKUMAR-0212** [comment]
Just checked with the code 

all affected pkgs and binaries are parsed and keep on reassigning to the var `affected`

![Screenshot 15-05-2024 at 15 25](https://github.com/canonical/ubuntu-security-notices/assets/119495918/71546dc1-b8d0-493c-b44e-302b9f74f625)

**Comment by dodys** [comment]
thanks for the report!
I've got a fix for it, I'm just running some checks but I should be pushing the fix soon
